### ISSUE TITLE
Upgrade app to Ember 3.22 (Part 1 of 2)

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/cli-guides#197]
## Problem

~Please wait till #198 has been completed and merged. Once that issue is complete, you should see `npm-run-all`, `ember-template-lint`, and `eslint` installed already.~ (This issue is unblocked now!)

If you run `npm outdated`, you will see that many packages can use an update. At the time of writing, I saw,

```bash
❯ npm outdated

Package                         Current   Wanted  Latest  Location
@ember/optional-features          1.3.0    1.3.0   2.0.0  @ember-learn/cli-guides
@glimmer/component                1.0.0    1.0.2   1.0.2  @ember-learn/cli-guides
@glimmer/tracking                 1.0.0    1.0.2   1.0.2  @ember-learn/cli-guides
alex                              7.1.0    7.1.0   9.0.1  @ember-learn/cli-guides
ember-auto-import                 1.5.3    1.6.0   1.6.0  @ember-learn/cli-guides
ember-cli                        3.16.1   3.16.2  3.21.2  @ember-learn/cli-guides
ember-cli-babel                  7.19.0   7.22.1  7.22.1  @ember-learn/cli-guides
ember-cli-fastboot                2.2.2    2.2.3   2.2.3  @ember-learn/cli-guides
ember-cli-htmlbars                4.3.1    4.4.0   5.3.1  @ember-learn/cli-guides
ember-cli-netlify                 0.3.1    0.3.1   0.4.1  @ember-learn/cli-guides
ember-cli-template-lint           1.0.0    1.0.0   2.0.2  @ember-learn/cli-guides
ember-data                       3.16.5   3.16.9  3.21.1  @ember-learn/cli-guides
ember-dictionary                  0.2.5    0.2.6   0.2.6  @ember-learn/cli-guides
ember-fetch                       7.1.0    7.1.0   8.0.2  @ember-learn/cli-guides
ember-resolver                    7.0.0    7.0.0   8.0.2  @ember-learn/cli-guides
ember-source                     3.16.8  3.16.10  3.21.1  @ember-learn/cli-guides
eslint-plugin-ember              7.13.0   7.13.0   9.0.0  @ember-learn/cli-guides
mocha                             5.2.0    5.2.0   8.1.3  @ember-learn/cli-guides
prember                           1.0.3    1.0.5   1.0.5  @ember-learn/cli-guides
qunit-dom                         1.2.0    1.5.0   1.5.0  @ember-learn/cli-guides
remark-cli                        8.0.0    8.0.1   8.0.1  @ember-learn/cli-guides
remark-lint                       7.0.0    7.0.1   7.0.1  @ember-learn/cli-guides
remark-preset-lint-consistent     3.0.0    3.0.1   3.0.1  @ember-learn/cli-guides
remark-preset-lint-recommended    4.0.0    4.0.1   4.0.1  @ember-learn/cli-guides
retext-indefinite-article         2.0.0    2.0.1   2.0.1  @ember-learn/cli-guides
unified                           9.0.0    9.2.0   9.2.0  @ember-learn/cli-guides
```

Moreover, the `cli-guides` app currently uses Ember `v3.16.8`. Let's upgrade the app to `v3.21.x` (or `v3.22.x` if it is available) for a regular maintenance.

### Part 1: Update packages

I may recommend updating packages in batches as shown below. (Hopefully, no major release introduced a breaking change that affects this app.)

After each batch update of packages, please push a commit so that the CI may check that lints and tests continue to pass.

- [ ] Update lint/test-related packages
  - alex
  - ~~Remove ember-cli-eslint, then install [eslint](https://github.com/eslint) to `devDependencies`~~
  - ~~Remove ember-cli-template-lint, then install [ember-template-lint](https://github.com/ember-template-lint/ember-template-lint) to `devDependencies`~~
  - eslint-plugin-ember
  - mocha
  - qunit-dom

- [ ] Update `remark`-related packages
  - remark-cli
  - remark-lint
  - remark-preset-lint-consistent
  - remark-preset-lint-recommended
  - retext-indefinite-article
  - unified

- [ ] Update Ember addons
  - ember-cli-fastboot
  - ember-cli-netlify
  - ember-dictionary
  - prember

- [ ] Update Ember-related packages (packages installed by default)
  - @ember/optional-features
  - @glimmer/component
  - @glimmer/tracking
  - ember-auto-import
  - ember-cli-babel
  - ember-cli-htmlbars
  - Remove ember-cli-uglify, then install [ember-cli-terser](https://github.com/ember-cli/ember-cli-terser) to `devDependencies`
  - ember-fetch
  - ember-resolver

- [ ] Update Ember with `ember-cli-update`
  - ember-cli
  - ember-data
  - ember-source

- [ ] ~~If running `ember-cli-update` didn't install `npm-run-all`, please install it under `devDependencies`. If it didn't _uninstall_ `ember-cli-eslint` and `ember-cli-template-lint`, please do so and install `eslint` and `ember-template-lint` instead.~~

**Comment by ijlee2** [comment]
General notes: Hi, everyone. To allow more people to participate in Hacktoberfest, please claim only 1 issue in this repo (unless there are no others who can help). 🙂

Please check `#hacktoberfest` on [Discord](https://discord.gg/emberjs) to find other repos that can use your help. Thanks and happy Hacktoberfest!

**Comment by maxwondercorn** [comment]
I can pick this one up
