### ISSUE TITLE
Epic - Document using scripts in package.json for common tasks

### ISSUE THREAD

**Issue by jenweber** [ember-learn/cli-guides#272]
This issue tracks the work to document [RFC 831](https://github.com/emberjs/rfcs/pull/831), Standardize use of package.json scripts

To do:
- [ ] Update language in ember-cli readme
- [ ] Update language in ember-cli instructions
- [ ] Update commands in the quickstart of this guide
- [ ] Update commands throughout the Ember Guides

**Comment by Shivareddy-Aluri** [comment]
@jenweber i can work on this. so we should encourage ppl to have the ember cli commands like ember server and ember test / ember exam inside the scripts in package.json and use it ?

**Comment by jenweber** [comment]
Hello! If you can help line up these changes, that would be great! However your PRs would not be able to be merged until after https://github.com/emberjs/rfcs/pull/831 is merged.

What we want to encourage is for people to use `npm serve` or `yarn serve` instead of `ember serve`. The scripts are already part of the blueprints in package.json (the files someone see when they create a new app).

Let me know if you have any other questions! Thanks for coming by to help!
