### ISSUE TITLE
Show the ember-cli logo instead of the generic Ember logo

### ISSUE THREAD

**Issue by mansona** [ember-learn/cli-guides#81]
For the cli-guides we should show the ember-cli logo in the top left. 

![image 2018-12-11 at 10 44 50 a m](https://user-images.githubusercontent.com/594890/49795425-dc892380-fd31-11e8-8239-cd57221df88f.png)

As we are using guidemaker for the ember-cli guides we will need to make this a configurable feature of the [guidemaker-ember-template](https://github.com/ember-learn/guidemaker-ember-template) so that it will default to the normal Ember logo.

### Todo

- [ ] add a configuration entry for `logo` to the guidemaker block of the cli-guides https://github.com/ember-learn/cli-guides/blob/master/config/environment.js#L33
  - I guess it doesn't really need to be in the guidemaker block 🤔 but it needs to be somewhere in that config
- [ ] Pass the logo into <EsNavbar> in ember-styleguide https://github.com/ember-learn/guidemaker-ember-template/blob/master/app/templates/application.hbs#L4
- [ ] make it so that `<EsNavbar>` supports having the logo passed into it https://github.com/ember-learn/ember-styleguide/blob/master/addon/components/es-navbar/template.hbs#L8

**Comment by villander** [comment]
@mansona I don't understand this question. Where are this logo? do you want me to put it in `guidemaker-ember-template`? and make it configurable?

**Comment by mansona** [comment]
@villander yes this would be a change to guidemaker-ember-template and it would need to be configurable (so it doesn't show up in other sites that use this template)

**Comment by cah-johnryan** [comment]
Hi @mansona,

In looking through this I see that the logo exists at https://github.com/emberjs/website/blob/master/source/images/brand/ember_CLI-Light.png.  

Are you ok with me creating a copy of this here: https://github.com/ember-learn/guidemaker-ember-template/tree/master/public/images/logos?  I don't readily know how else I can make this asset available in the guidemaker repo without porting it over.

Regardless. I plan to try and assemble PR's for this.  Thanks.
